config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'items#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'

    resources :users

    resources :warehouses do
      get :addresses,   on: :member
      get :information, on: :member
    end

    resources :addresses do
      get :import_addresses, on: :collection
      post :import,          on: :collection
    end

    resources :items do
      get :import_items, on: :collection
      post :import,      on: :collection
    end

    resources :receipts do
      get :receipt_transactions, on: :collection
    end

    resources :expenses do
      get :expense_transactions, on: :collection
    end

    resources :relocates do
      get :relocate_transactions, on: :collection
    end

    resources :stocks

    resources :orders do
      patch :update_quantity,   on: :member
      patch :order_cancelation, on: :member
      get :get_order,           on: :member
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  #  validates :quantity, numericality: { greater_than: 0 }

  enum :status, { created: 0, confirmed: 1, finished: 2, canceled: 3 }, default: :created

  belongs_to :item
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :find_order, only: %i[show edit update_quantity get_order order_cancelation]
  def index
    @orders = Order.all
  end

  def show; end

  def edit
    authorize @order
  end

  def update_quantity
    authorize @order
    if @order.status.in?(%w[created confirmed])
      if @order.update(order_params)
        @order.update(status: 'confirmed', responsible: current_user.username)
        flash[:success] = 'Данные изменены'
        redirect_to @order
      else
        flash[:error] = 'Данные не изменены'
        redirect_to edit_item_path(@order)
      end
    else
      flash[:error] = 'Заказ не может быть изменен, так как его статус не позволяет этого'
      redirect_to @order
    end
  end

  def get_order
    authorize @order
  end

  def order_cancelation
    authorize @order
    if @order.update(status: 'canceled')
      flash[:success] = 'Заказ отменен'
      redirect_to @order
    else
      flash[:error] = 'Заказ не отменен'
      redirect_to order_path(@order)
    end
  end

  private

  def order_params
    params.require(:order).permit(:quantity, :status, :responsible)
  end

  def find_order
    @order = Order.find_by(id: params[:id])
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/edit.html.erb
<h4>Редактирование заказа</h4>
<br />
<%= form_with(model: @order, url: update_quantity_order_path(@order), method: :patch, local: true) do |form| %>
  <div class="field">
    <p>
      <td><%= @order.id %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @order.item.number %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @order.status %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <%= form.text_field :quantity, placeholder: "Введите количество" %>
    </p>
  </div>
  
  <div class="actions">
    <p>
      <%= form.submit "Подтвердить" %>
    </p>
  </div>
<% end %>

app/views/orders/get_order.html.erb
<h4>Отмена заказа</h4>
<br />
<%= form_with(model: @order, url: order_cancelation_order_path(@order), method: :patch, local: true) do |form| %>
  <div class="field">
    <p>
      <td><%= @order.id %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @order.item.number %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @order.status %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @order.quantity %></td>
    </p>
  </div>
  
  <div class="actions">
    <p>
      <%= form.submit "Подтвердить" %>
    </p>
  </div>
<% end %>

app/views/orders/index.html.erb
<h4>Заказы</h4>
<br />
<table class="table">
  <thead>
    <tr>
      <th>Номер заказа</th>
      <th>Номер товара</th>
      <th>Количество</th>
      <th>Статус</th>
      <th>Ответственный</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.item.number %></td>
        <td><%= order.quantity %></td>
        <td><%= order.status %></td>
        <td><%= order.responsible %></td>
        <td><%= link_to 'Редактировать', edit_order_path(order) %></td>
        <td><%= link_to 'Отменить', get_order_order_path(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<%= @order.id %>
<%= @order.item.number %>
<%= @order.quantity %>
<%= @order.status %>