config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'items#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'

    resources :users

    resources :warehouses do
      get :addresses,   on: :member
      get :information, on: :member
    end

    resources :addresses do
      get :import_addresses, on: :collection
      post :import,          on: :collection
    end

    resources :items do
      get :import_items, on: :collection
      post :import,      on: :collection
    end

    resources :receipts do
      get :receipt_transactions, on: :collection
    end

    resources :expenses do
      get :expense_transactions, on: :collection
    end

    resources :relocates do
      get :relocate_transactions, on: :collection
    end

    resources :stocks

    resources :orders do
      patch :update_quantity,   on: :member
      patch :order_cancelation, on: :member
      get :get_order,           on: :member
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :description, presence: true

  has_many :receipts, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :relocates, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :find_item, only: %i[show edit update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item
    if @item.save
      flash[:success] = 'Новый товар создан'
      redirect_to @item
    else
      flash[:error] = 'Заполните все поля'
      redirect_to new_item_path
    end
  end

  def show; end

  def edit
    authorize @item
  end

  def update
    authorize @item
    if @item.update(item_params)
      flash[:success] = 'Данные изменены'
      redirect_to @item
    else
      flash[:error] = 'Данные не изменены'
      redirect_to edit_item_path(@item)
    end
  end

  def import_items; end

  def import
    file = params[:file]

    if file.content_type == 'text/csv'
      CsvImportItemsService.new.call(file)
      flash[:success] = 'Товары загружены'
    else
      flash[:error] = 'Только файл формата csv'
    end
    redirect_to import_items_items_path
  end

  private

  def item_params
    params.require(:item).permit(:number, :description, :minimal_quantity)
  end

  def find_item
    @item = Item.find_by(id: params[:id] || params[:item_id])
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/add_address.html.erb
<h4>Размещение в адресную ячейку</h4>

<%= form_with model: @item, url: add_address_item_path(@item) do |form| %>
  <div class="field">
    <%= form.label :address_id, "Адресная ячейка" %>
    <%= form.collection_select :address_id, @addresses, :id, :name, prompt: 'Выберите ячейку' %>
  </div>
  
  <div class="actions">
    <%= form.submit "Разместить" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h4>Редактирование товара</h4>
<br />
<%= form_with model: @item, local: true do |form| %>
  <div class="field">
    <p>
      <td><%= @item.number %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <td><%= @item.description %></td>
    </p>
  </div>

  <div class="field">
    <p>
      <%= form.text_field :minimal_quantity, placeholder: "Введите минимальный запас" %>
    </p>
  </div>
  
  <div class="actions">
    <p>
      <%= form.submit "Создать товар" %>
    </p>
  </div>
<% end %>

app/views/items/get_address.html.erb
<h4>Размещение в адресную ячейку</h4>
<br />
<%= form_with model: @item, url: put_item_on_address_item_path(@item), method: :patch do |form| %>
  <div class="field">
    <p>
      <%= form.collection_select :address_id, @addresses, :id, :name, prompt: "Выберите адрес" %>
    </p>  
  </div>
  
  <div class="actions">
    <p>
      <%= form.submit "Разместить" %>
    </p>  
  </div>
<% end %>

app/views/items/import_items.html.erb
<h4>Загрузка товара</h4>
<br />
<%= form_with url: import_items_path, method: :post do |form| %>
  <%= form.file_field :file, accept: ".csv" %>
  <%= form.button "Загрузить" %>
<% end %>

app/views/items/index.html.erb
<h4>Остатки товаров на складах</h4>
<br />
<table class="table">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Наименование</th>
      <th>Минимальный запас</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.number, edit_item_path(item) %></td>
        <td><%= item.description %></td>
        <td><%= item.minimal_quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h4>Новый товар</h4>
<br />
<%= form_with model: @item, url: items_path, method: :post, local: true do |form| %>
  <div class="field">
    <p>
      <%= form.text_field :number, placeholder: "Введите номер товара" %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= form.text_field :description, placeholder: "Введите наименование товара" %>
    </p>
  </div>
  
  <div class="actions">
    <p>
      <%= form.submit "Создать товар" %>
    </p>
  </div>
<% end %>

app/views/items/show.html.erb
<%= @item.number %>
<%= @item.description %>