config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'items#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'

    resources :users

    resources :warehouses do
      get :addresses,   on: :member
      get :information, on: :member
    end

    resources :addresses do
      get :import_addresses, on: :collection
      post :import,          on: :collection
    end

    resources :items do
      get :import_items, on: :collection
      post :import,      on: :collection
    end

    resources :receipts do
      get :receipt_transactions, on: :collection
    end

    resources :expenses do
      get :expense_transactions, on: :collection
    end

    resources :relocates do
      get :relocate_transactions, on: :collection
    end

    resources :stocks

    resources :orders do
      patch :update_quantity,   on: :member
      patch :order_cancelation, on: :member
      get :get_order,           on: :member
    end
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :warehouse_id }

  belongs_to :warehouse
  has_many :receipts, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :relocates, dependent: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def check_stock
    stock = Stock.find_or_initialize_by(item: item, address: address)

    if stock.new_record?
      errors.add(:base, 'Товар отсутствует на данном адресе')
    elsif stock.quantity < quantity
      errors.add(:quantity, 'Не достаточно товара на адресе')
    end

    throw(:abort) if errors.any?
  end
end

app/models/expense.rb
# frozen_string_literal: true

class Expense < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  belongs_to :address
  belongs_to :item

  after_save :update_stock
  before_save :check_stock

  private

  def update_stock
    stock = Stock.find_or_initialize_by(item: item, address: address)
    stock.quantity = (stock.quantity || 0) - quantity
    stock.save
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :description, presence: true

  has_many :receipts, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :relocates, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  #  validates :quantity, numericality: { greater_than: 0 }

  enum :status, { created: 0, confirmed: 1, finished: 2, canceled: 3 }, default: :created

  belongs_to :item
end

app/models/receipt.rb
# frozen_string_literal: true

class Receipt < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  belongs_to :address
  belongs_to :item

  after_save :update_stock

  private

  def update_stock
    stock = Stock.find_or_initialize_by(item: item, address: address)
    stock.quantity = (stock.quantity || 0) + quantity
    stock.save
  end
end

app/models/relocate.rb
# frozen_string_literal: true

class Relocate < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :relocated_to, presence: true

  belongs_to :item
  belongs_to :address
  belongs_to :relocated_to, class_name: 'Address'

  after_save :update_stock
  before_save :check_stock

  private

  def update_stock
    stock_from = Stock.find_or_initialize_by(item: item, address: address)
    stock_from.quantity = (stock_from.quantity || 0) - quantity
    stock_from.save

    stock_to = Stock.find_or_initialize_by(item: item, address: relocated_to)
    stock_to.quantity = (stock_to.quantity || 0) + quantity
    stock_to.save
  end
end

app/models/stock.rb
# frozen_string_literal: true

class Stock < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :address
  belongs_to :item
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse.rb
# frozen_string_literal: true

class Warehouse < ApplicationRecord
  before_save :capitalize_name, :upcase_warehouse_code

  validates :name, presence: true, uniqueness: true
  validates :warehouse_code, presence: true, uniqueness: true

  has_many :addresses, dependent: :destroy
  has_many :receipts, through: :addresses
  has_many :expenses, through: :addresses

  private

  def capitalize_name
    self.name = name.downcase.capitalize if name.present?
  end

  def upcase_warehouse_code
    self.warehouse_code = warehouse_code.upcase if warehouse_code.present?
  end
end

app/helpers/adresses_helper.rb
# frozen_string_literal: true

module AdressesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/expenses_helper.rb
# frozen_string_literal: true

module ExpensesHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/receipts_helper.rb
# frozen_string_literal: true

module ReceiptsHelper
end

app/helpers/relocates_helper.rb
# frozen_string_literal: true

module RelocatesHelper
end

app/helpers/stocks_helper.rb
# frozen_string_literal: true

module StocksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/warehouses_helper.rb
# frozen_string_literal: true

module WarehousesHelper
end

app/views/include/_main_menu.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="<%=  %>">Поиск</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarSupportedContent" class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Поступление
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Поступление товара", new_receipt_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Транзакции", receipt_transactions_receipts_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Выдача
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Выдача товара", new_expense_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Транзакции", expense_transactions_expenses_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Перемещение
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Перемещение товара", new_relocate_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Транзакции", relocate_transactions_relocates_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Склад
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Все склады", warehouses_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Создать склад", new_warehouse_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Товар
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Все товары", items_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Остатки товаров", stocks_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Создать товар", new_item_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Заказы", orders_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Загрузка
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Загрузка товара", import_items_items_path, class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Загрузка адресов", import_addresses_addresses_path, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Профиль", user_path(current_user), class: "btn btn-link dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= button_to "Выйти", destroy_user_session_path, method: :delete, class: "btn btn-link dropdown-item" %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/include/_notification.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger flash" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<% if flash[:success].present? %>
  <div class="alert alert-success flash" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag "flash" %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= render 'include/main_menu', locals: { item: @item } %>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'include/notification' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>